env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_EMULATOR_LEVEL=2
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20
language: android
android:
components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
    - android-$ANDROID_EMULATOR_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL
sudo: false   
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+ 
jdk:
  - oraclejdk8
before_script :
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./licenses/* "$ANDROID_HOME/licenses"
    - android list targets
    # Create and start emulator.
    #- echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
    #- emulator -avd test -no-window &
    #- android-wait-for-emulator
    #- adb shell input keyevent 82 &
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
   - ./gradlew test
   #- ./gradlew build jacocoTestReport assembleAndroidTest
   #- ./gradlew build connectedCheck
after_success:
    #- bash <(curl -s https://codecov.io/bash)
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"   
