sudo: required
language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
script:
    - ./gradlew test
licenses:
    - 'android-sdk-preview-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
    - yes | sdkmanager "platforms;android-28"
